# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/home/dual/cs5200444/Desktop/assignment 2/mlp/mlp.cache/wt} [current_project]
set_property parent.project_path {/home/dual/cs5200444/Desktop/assignment 2/mlp/mlp.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {/home/dual/cs5200444/Desktop/assignment 2/mlp/mlp.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  {/home/dual/cs5200444/Desktop/assignment 2/weights_bias.mif}
  {/home/dual/cs5200444/Desktop/assignment 2/imgdata_digit7.mif}
  {/home/dual/cs5200444/Desktop/assignment 2/imgdata_digit0.mif}
  {/home/dual/cs5200444/Desktop/assignment 2/imgdata_digit6.mif}
  {/home/dual/cs5200444/Desktop/assignment 2/imgdata_digit3.mif}
  {/home/dual/cs5200444/Desktop/assignment 2/imgdata_digit1.mif}
  {/home/dual/cs5200444/Desktop/assignment 2/imgdata_digit4.mif}
  {/home/dual/cs5200444/Desktop/assignment 2/imgdata_digit5.mif}
  {/home/dual/cs5200444/Desktop/assignment 2/imgdata_digit2.mif}
}
read_vhdl -library xil_defaultlib {
  {/home/dual/cs5200444/Desktop/assignment 2/ram.vhd}
  {/home/dual/cs5200444/Desktop/assignment 2/comparator.vhd}
  {/home/dual/cs5200444/Desktop/assignment 2/rom.vhd}
  {/home/dual/cs5200444/Desktop/assignment 2/seven_seg.vhd}
  {/home/dual/cs5200444/Desktop/assignment 2/shifter.vhd}
  {/home/dual/cs5200444/Desktop/assignment 2/mac.vhd}
  {/home/dual/cs5200444/Desktop/assignment 2/mlp.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{/home/dual/cs5200444/Desktop/assignment 2/mlp.xdc}}
set_property used_in_implementation false [get_files {{/home/dual/cs5200444/Desktop/assignment 2/mlp.xdc}}]


synth_design -top mlp -part xc7a35tcpg236-1


write_checkpoint -force -noxdef mlp.dcp

catch { report_utilization -file mlp_utilization_synth.rpt -pb mlp_utilization_synth.pb }
